# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Dotty < Formula
  desc "Dotfiles using symlinks and embedded git"
  homepage "https://github.com/keithhendry/dotty"
  url "https://github.com/keithhendry/dotty/archive/0.1.0.tar.gz"
  sha256 "498c2ae6820344990171ab515f1d4df309dd538091c676ffb6dae2d20d3695a2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/keithhendry/dotty/releases/download/0.1.0/dotty-0.1.0-darwin-amd64.tar.gz"
      sha256 "d0ea04a71f843a966d44199611cf9e2169942ee88bf81596052e373890787b82"
    end

    on_arm do
      url "https://github.com/keithhendry/dotty/releases/download/0.1.0/dotty-0.1.0-darwin-arm64.tar.gz"
      sha256 "7c71ab1b265d487e77486c6002c00163e265bda7007d6656e28783ed79c29dae"
    end
  end

  def install
    bin.install "dotty"
  end

  test do
    system "#{bin}/dotty --version"
  end
end
