name: Create PR
on:
  push:
    branches:
      - release/*
jobs:
  build:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create pr
        run: |
          pr_url="$(gh pr create --fill)"
          gh pr merge --auto -r "$pr_url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
